"""init schema (final)

Revision ID: 426bf2cfc356
Revises: 
Create Date: 2025-10-22 15:01:55.411819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '426bf2cfc356'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.String(), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('is_relevant', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.String(), server_default="(datetime('now')", nullable=True),
    sa.CheckConstraint('is_relevant IN (0, 1)', name='ck_feedback_is_relevant'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ingredients', sa.Text(), nullable=False),
    sa.Column('cuisine', sa.Text(), nullable=False),
    sa.Column('diet', sa.String(), server_default='none', nullable=False),
    sa.Column('time_minutes', sa.Integer(), nullable=False),
    sa.Column('popularity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    op.drop_table('feedback')
    # ### end Alembic commands ###
