services:
  - type: web
    name: recipe-api
    env: docker
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    dockerfilePath: Dockerfile.api
    envVars:
      - key: APP_ENV
        value: "prod"
      - key: DATA_DIR
        value: "/tmp"
      # IMPORTANT: set this after the UI is live (or now, if you know the UI URL)
      # - key: CORS_ALLOW_ORIGINS
      #   value: "https://<your-ui>.onrender.com"

  - type: web
    name: recipe-ui
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: Dockerfile.ui
    envVars:
      - key: API_URL
        value: "https://recipe-api-81x3.onrender.com"  # <-- put your live API URL here (no trailing slash)
