services:
  - type: web
    name: recipe-api
    env: docker
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    dockerfilePath: Dockerfile.api
    envVars:
      - key: APP_ENV
        value: "prod"
      - key: DATA_DIR
        value: "/tmp"
